[Looker]
# Base URL for API. Do not include /api/* in the url.
base_url=https://your.looker.com:
# API 3 client id
client_id=YourClientID
# API 3 client secret
client_secret=YourClientSecret
# Set to false if testing locally against self-signed certs. Otherwise leave True
verify_ssl=True