name: Check documentation freshness

on: [push]

env:
  NODE_VERSION: 16.x

jobs:
  doccheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Try to generate docs
      run: npm run docs

    - name: Check for uncommitted doc files
      # Returns 1 if there are uncomitted files in docs/
      run: git diff --exit-code docs